package cli

import "strings"

// Args is a minimal positional / option / flag parser with no dependencies.
//
// Conventions:
//   - Positionals: any argument not starting with "--".
//   - Options: "--name value" or "--name=value". A repeated option keeps its last value.
//   - Flags: "--name" with no following value (the end of the arguments, or another "--…").
//
// Hooks generated by older installs pass arguments in exactly these shapes, so the rules stay
// as they are, quirks included: an option name followed by a non-option word always takes that
// word as its value.
type Args struct {
	Positionals []string
	Options     map[string]string
	Flags       map[string]bool
}

// ParseArgs splits args into positionals, options and flags.
func ParseArgs(args []string) Args {
	p := Args{Options: map[string]string{}, Flags: map[string]bool{}}
	for i := 0; i < len(args); i++ {
		a := args[i]
		if !strings.HasPrefix(a, "--") {
			p.Positionals = append(p.Positionals, a)
			continue
		}
		if key, value, ok := strings.Cut(a, "="); ok {
			p.Options[key] = value
		} else if i+1 < len(args) && !strings.HasPrefix(args[i+1], "--") {
			p.Options[a] = args[i+1]
			i++
		} else {
			p.Flags[a] = true
		}
	}
	return p
}

// Positional is the index-th positional argument; ok is false when there are fewer.
func (p Args) Positional(index int) (string, bool) {
	if index < 0 || index >= len(p.Positionals) {
		return "", false
	}
	return p.Positionals[index], true
}

// Option is the value of the option name ("--tool"); ok is false when it was not given.
func (p Args) Option(name string) (string, bool) {
	v, ok := p.Options[name]
	return v, ok
}

// Flag reports whether the flag name ("--dry-run") was given without a value.
func (p Args) Flag(name string) bool { return p.Flags[name] }
